home_work-7/server/main/urls.py
from django.urls import path
from .views import (
    index, about, contacts
)

app_name = 'main'

urlpatterns = [
    path('contacts/', contacts, name='contacts'),
    path('about/', about, name='about'),
    path('', index, name='main'),
]

home_work-7/server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import (
    product_list_view
)

router = [
    path('products/', include('products.routes')),
    path('categories/', include('products.routes.categories')),
]

urlpatterns = [
    path('api/', include(router)),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_work-7/server/products/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(
        max_length=255
    )

    description = models.TextField(
        blank=True,
        null=True,
    )

    created = models.DateTimeField(
        auto_now_add=True,
    )

    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(
        max_length=255
    )

    image = models.ImageField(
        upload_to='products',
        blank=True,
        null=True,
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    description = models.TextField(
        blank=True,
        null=True,
    )

    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0
    )

    created = models.DateTimeField(
        auto_now_add=True,
    )

    modified = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

home_work-7/server/products/forms/categories.py
from django import forms

from products.models import Category


class CategoryForm(forms.Form):
    name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                'class': 'model-form'
            }
        )
    )

    description = forms.CharField(
        widget=forms.widgets.Textarea(
            attrs={
                'class': 'model-form'
            }
        )
    )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']
        widgets = {
            'name': forms.widgets.TextInput(
                attrs={
                    'class': 'model-form'
                }
            ),
            'description': forms.widgets.Textarea(
                attrs={
                    'class': 'model-form'
                }
            )
        }

home_work-7/server/products/forms/products.py
from django  import forms

from products.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name', 'image', 'category',
            'description', 'cost'
        ]

home_work-7/server/products/routes/categories.py
from django.urls import path
from products.views import (
    RestCategoryListView
)


app_name = 'rest_categories'

urlpatterns = [
    path('', RestCategoryListView.as_view(), name='list'),
]

home_work-7/server/products/routes/products.py
from django.urls import path
from products.views import (
    RestProductListView
)


app_name = 'rest_products'

urlpatterns = [
    path('', RestProductListView.as_view(), name='list'),
]

home_work-7/server/products/views/categories.py
import json 
from django.shortcuts import (
    render, redirect
)
from django.views.generic import (
    ListView, DetailView, CreateView, 
    UpdateView, DeleteView
)
from django.core.paginator import Paginator
from django.urls import reverse, reverse_lazy
from django.http import Http404, JsonResponse

from products.models import Category
from products.forms import CategoryForm, CategoryModelForm


class RestCategoryListView(ListView):
    model = Category

    def serialize_object_list(self, queryset):
        return list(
            map(
                lambda itm: {
                    'id': itm.id,
                    'name': itm.name
                },
                queryset
            )
        )

    def get_context_data(self, **kwargs):
        context = super(RestCategoryListView, self).get_context_data(**kwargs)
        object_list = context.get('object_list')

        data = {}
        data['results'] = self.serialize_object_list(object_list)

        return data 

    def render_to_response(self, context, **response_kwargs):
        return JsonResponse(context)


class CategoryListView(ListView):
    model = Category
    template_name = 'categories/products.html'

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'categories/detail.html'
    

    def get_context_data(self, **kwargs):
        key = self.context_object_name if self.context_object_name else 'object'
        obj = kwargs.get(key)
        products = obj.product_set.all()
        page = self.request.GET.get('page')
        
        paginator = Paginator(products, 10)

        page_obj = paginator.get_page(page)

        return {
            key: obj,
            'products':page_obj
        }


class CategoryCreateView(CreateView):
    model = Category
    form_class = CategoryModelForm
    template_name = 'categories/create.html'
    success_url = reverse_lazy('categories:list')


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryModelForm
    template_name = 'categories/update.html'
    success_url = reverse_lazy('categories:list')


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'categories/delete.html'
    success_url = reverse_lazy('categories:list')

def category_create_view(request):
    form = CategoryModelForm()
    success_url = reverse('products:list')

    if  request.method == 'POST':
        form = CategoryModelForm(data=request.POST)

        if form.is_valid():
            form.save()

            # obj = Category(
            #     name=form.cleaned_data.get('name'),
            #     description=form.cleaned_data.get('description'),
            # )
            # obj.save()

            return redirect(success_url)

    return render(
        request,
        'categories/create.html',
        {'form': form}
    )


def category_update_view(request, pk):
    try:
        obj = Category.objects.get(pk=pk)
    except Exception as err:
        raise Http404

    form = CategoryModelForm(instance=obj)
    success_url = reverse('products:list')

    if request.method == 'POST':
        form = CategoryModelForm(
            request.POST,
            files=request.FILES,
            initial=obj
        )

        if form.is_valid():
            form.save()

            return redirect(success_url)
    return render(
        request,
        'categories/update.html',
        {'form':form}
    )

home_work-7/server/products/views/products.py
import json 
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin
)
from django.core.paginator import Paginator
from django.views.generic import (
    ListView, DetailView, CreateView, 
    UpdateView, DeleteView
)
from django.urls import reverse, reverse_lazy
from django.http import Http404, JsonResponse

from products.models import Product
from products.forms import ProductForm


class RestProductListView(ListView):
    model = Product
    paginate_by = 2

    def serialize_object_list(self, queryset):
        return list(
            map(
                lambda itm: {
                    'id': itm.id,
                    'name': itm.name,
                    'category': itm.category.name if itm.category else None,
                    'image': itm.image.url if itm.image else None,
                    'cost': itm.cost
                },
                queryset
            )
        )

    def get_context_data(self, **kwargs):
        context = super(RestProductListView, self).get_context_data(**kwargs)

        data = {}
        page = context.get('page_obj')
        router_url = reverse('rest_products:list')

        data['next_url'] = None
        data['previous_url'] = None
        data['page'] = page.number
        data['count'] = page.paginator.count
        data['results'] = self.serialize_object_list(page.object_list)

        if page.has_previous():
            data['previous_url'] = f'{router_url}?page={page.previous_page_number()}'
        
        if page.has_next():
            data['next_url'] = f'{router_url}?page={page.next_page_number()}'

        return data

    def render_to_response(self, context, **response_kwargs):
        return JsonResponse(context)


class ProductListView(ListView):
    model = Product
    template_name = 'products/products.html'
    paginate_by = 10

    # def get_context_data(self, **kwargs):
    #     context = super(ProductListView, self).get_context_data(**kwargs)
    #     queryset = context.get('object_list')
    #     page = self.request.GET.get('page')

    #     paginator = Paginator(queryset, 2)

    #     page_obj = paginator.get_page(page)

    #     context['page_obj'] = page_obj

    #     return context
        

class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/detail.html'
    context_object_name = 'inst'


class ProductCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'products/create.html'
    success_url = reverse_lazy('products:list')
    login_url = reverse_lazy('accounts:login')

    def test_func(self):
        return self.request.user.has_perm('products.add_product')


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = [
        'name', 'image', 'category',
        'description', 'cost'
    ]
    template_name = 'products/update.html'
    success_url = reverse_lazy('products:list')
    login_url = reverse_lazy('accounts:login')

    def test_func(self):
        return self.request.user.has_perm('products.change_product')


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:list')
    login_url = reverse_lazy('accounts:login')

    def test_func(self):
        return self.request.user.is_superuser


def product_list_view(request):
    # with open('products/fixtures/data/data.json') as file:
    #     data = json.load(file)

    data = Product.objects.all()

    return render(
        request,
        'products/products.html',
        {'object_list': data}
    )

def product_detail_view(request, pk):
    # with open('products/fixtures/data/data.json') as file:
    #     data = json.load(file)

    data = Product.objects.get(pk=pk)

    return render(
        request,
        'products/detail.html',
        {'inst': data}
        # {'object': data[idx]}
    )
@login_required(login_url=reverse_lazy('accounts:login'))
def product_create_view(request):
    form = ProductForm()
    success_url = reverse('products:list')

    if  request.method == 'POST':
        form = ProductForm(data=request.POST)

        if form.is_valid():
            form.save()


            return redirect(success_url)

    return render(
        request,
        'products/create.html',
        {'form': form}
    )

@login_required(login_url=reverse_lazy('accounts:login'))
def product_update_view(request, pk):
    obj = get_object_or_404(Product, pk=pk)

    form = ProductForm(instance=obj)
    success_url = reverse('products:list')

    if request.method == 'POST':
        form = ProductForm(
            request.POST,
            files=request.FILES,
            instance=obj
        )

        if form.is_valid():
            form.save()

            return redirect(success_url)
    return render(
        request,
        'products/update.html',
        {'form': form}
    )

@login_required(login_url=reverse_lazy('accounts:login'))
def product_delete_view(request, pk):
    obj = get_object_or_404(Product, pk=pk)
    success_url = reverse('products:list')

    if request.method == 'POST':
        obj.delete()

        return redirect(success_url)


    return render(
    request,
    'products/delete.html',
    {'object': obj}
)

home_work-7/server/server/templates/server/form.html
<form action="" method="POST">
    {% csrf_token %}

    {% for err in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        <span class="">{err}</span>
    </div>
    {% endfor %}

    {% for field in form %}
    <div class="field-group">
        <label for="{{ field.name }}">{{ field.label }}</label>
        {{ field }}

        {% for err in field.errors %}
        <small class="field__error">{{ err }}</small>
        {% endfor %}
    </div>
    {% endfor %}
    <input type="submit">
</form>

home_work-7/server/server/templates/server/master.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>
        {% block page_title %}
        {% endblock %}
    </title>

    {% block page_static %}
    {% endblock %}

    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'server/css/master.css' %}" />
</head>

<body>
    <div class="page">
        <header class="page__header">
            <nav class="page__navigation">
                <ul class="navigation-list">
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            Главная
                        </span>
                        <a href="{% url 'main:main' %}" class="navigation-list__item-link">
                        </a>
                    </li>
                    <li class="navigation-list__item">
                        <span class="navigation-list__item-text">
                            Витрина
                        </span>
                        <a href="{% url 'products:list' %}" class="navigation-list__item-link">
                         </a>
                     </li>
                     <li class="navigation-list__item">
                         <span class="navigation-list__item-text">
                             О проекте
                         </span>

                        <a href="{% url 'main:about' %}" class="navigation-list__item-link">
                         </a>
                     </li>
                     <li class="navigation-list__item">
                         <span class="navigation-list__item-text">
                             Контакты
                         </span>

                        <a href="{% url 'main:contacts' %}" class="navigation-list__item-link">
                         </a>
                     </li>
                 </ul>
            </nav>
        </header>
        <div class="page__content">
            <ul class="categories"></ul>

            {% block page_content %}
            {% endblock %}

        </div>
        <footer class="page__footer">
            <span class="page__copyright">
                © GeekBrains
            </span>
        </footer>
    </div>
    {% block page_js %}
    {% endblock %}
    <script src="{% static 'server/js/categories.js' %}"></script>
    <script>
        const categories = document.querySelector('.categories');
        
        const categoriesUrl = '{% url "rest_categories:list" %}'

        const renderCategoryList = () => {
            
            fetch(categoriesUrl)
                .then(response => response.json())
                .then(
                    data => (
                        data.results.reduce(
                            (val, itm, idx) => val += renderCategory(itm)
                        )
                    )
                )
                .then(
                    renderString => {
                        categories.innerHTML = renderString
                    }
                )
        }

        document.addEventListener("DOMContentLoaded", renderCategoryList);
    </script>

</body>
</html>

home_work-7/server/server/templates/server/pagination.html
<ul class="pagination">
        {% if page.has_previous %}
        <li class="pagination__link_prev">
            <a href="?page={{ page.previous_page_number }}">
                Назад
            </a>
        </li>
        {% endif %}
        {% for num in page_range %}
        <li class="pagination__link">
            <a href="?page={{ num }}">
                    {{ num }}
            </a>
        </li>
        {% endfor %}
        {% if page.has_next %}
        <li class="pagination__link_next">
            <a href="?page={{ page.next_page_number }}">
                Далее
            </a>
        </li>
        {% endif %}
    </ul>

home_work-7/server/server/templates/server/product.html
{% load static %}

<div class="products__item">
    {% if image %}
    <img class="products__item-image" src="{{ image.url }}" alt="{{ name }}">
    {% else %}
    <img class="products__item-image products__item-image_empty" src="{% static 'products/images/empty.png' %}" alt="empty">
    {% endif %}
    <span class="products__item-name">
        {{ name|default:"По умолчанию"|title }}
    </span>
    <span class="products__item-description">
        {{ description }}
    </span>
    {% if cost %}
    <span class="products__item-cost">
        {{ cost }}
    </span>
    {% else %}
    <span class="products__item-cost products__item-cost_empty">
        Значение отсутствует
    </span>
    {% endif %}
    <a href="{% url 'products:detail' pk=id %}" class="products__item-link">
        Ссылка на {{ name|lower }}
    </a>
</div>